import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PUBLISH = ROOT / "statniceucenie-publish"
TOPICS = PUBLISH / "data/topics.json"
OUTPUT = PUBLISH / "kostry/data.js"


S = {
    "ekonomia-1": ("Táto otázka spája fungovanie trhu s ukazovateľmi vývoja ekonomiky.", [
        "Dopyt: koľko chcú a môžu zákazníci kúpiť; pri vyššej cene zvyčajne klesá.",
        "Ponuka: koľko chcú výrobcovia predať; pri vyššej cene zvyčajne rastie.",
        "Rovnováha vzniká, keď sa dopyt rovná ponuke; inak vzniká prebytok alebo nedostatok.",
        "Manažér sleduje cenu, dopyt, náklady, konkurenciu a makroekonomické premenné.",
        "Makroekonomické premenné sú najmä HDP, inflácia, nezamestnanosť, úroky a výmenný kurz.",
        "Časový rad rozkladáme na trend, sezónnosť, cyklus a náhodnú zložku.",
    ]),
    "ekonomia-2": ("Pri cenotvorbe musí manažér vedieť, ako zákazníci reagujú na zmenu ceny.", [
        "Cenová elasticita meria percentuálnu zmenu dopytu po zmene ceny.",
        "Elastický dopyt reaguje výrazne; neelastický reaguje slabo.",
        "Krížová elasticita sleduje vzťah substitútov a komplementov.",
        "Dôchodková elasticita sleduje reakciu dopytu na zmenu príjmu.",
        "Pri cene manažér zohľadňuje aj náklady, konkurenciu, cieľ firmy a vnímanú hodnotu.",
        "Korelácia meria silu vzťahu; regresia ho vyjadrí rovnicou a umožní odhad.",
    ]),
    "ekonomia-3": ("Trhové štruktúry sa líšia počtom firiem, produktom a možnosťou ovplyvniť cenu.", [
        "Dokonalá konkurencia: veľa firiem, rovnaký produkt, cenu určuje trh.",
        "Monopolistická konkurencia: veľa firiem, ale odlíšené produkty.",
        "Oligopol: niekoľko veľkých firiem, ktoré navzájom sledujú svoje rozhodnutia.",
        "Monopol: jeden dodávateľ, vysoké bariéry vstupu a často regulácia.",
        "Na Slovensku: poľnohospodárstvo, kaviarne, operátori a sieťové odvetvia.",
    ]),
    "ekonomia-4": ("HDP meria produkciu na území krajiny, kým HNP sleduje produkciu jej obyvateľov a firiem.", [
        "HDP možno vypočítať produkčnou, dôchodkovou alebo výdavkovou metódou.",
        "Výdavková metóda: C + I + G + čistý export.",
        "Platobná bilancia zachytáva ekonomické vzťahy so zahraničím.",
        "Má bežný, kapitálový a finančný účet.",
        "Vývoj SR za poslednú dekádu ovplyvnili rast pred pandémiou, prepad v roku 2020 a následné oživenie s infláciou.",
        "HDP neukazuje rozdelenie bohatstva, zdravie, voľný čas ani životné prostredie.",
    ]),
    "ekonomia-5": ("Inflácia a nezamestnanosť patria medzi základné ukazovatele stavu ekonomiky.", [
        "Nezamestnanosť môže byť frikčná, štrukturálna alebo cyklická.",
        "Inflácia znamená rast všeobecnej cenovej hladiny a pokles kúpnej sily.",
        "Phillipsova krivka krátkodobo ukazuje nepriamy vzťah inflácie a nezamestnanosti.",
        "Menová, fiškálna a štrukturálna politika ovplyvňujú infláciu aj zamestnanosť.",
        "Aktívna politika vytvára prácu a vzdeláva; pasívna vypláca dávky.",
        "CPI a HICP sledujú spotrebiteľské ceny, PPI ceny výrobcov, deflátor celé HDP.",
        "V SR nezamestnanosť dlhodobo klesala, pandémia ju dočasne zvýšila a po roku 2021 prudko rástla inflácia.",
    ]),
    "ekonomia-6": ("Fiškálna politika je pôsobenie vlády na ekonomiku cez dane a verejné výdavky.", [
        "Expanzívna: vyššie výdavky alebo nižšie dane podporia dopyt a rast.",
        "Reštriktívna: nižšie výdavky alebo vyššie dane tlmia infláciu a deficit.",
        "Nástroje sú dane, transfery, verejné nákupy a investície.",
        "Firmám mení náklady a dopyt; domácnostiam disponibilný príjem a spotrebu.",
        "Slovensko po krízovej expanzii prešlo ku konsolidácii verejných financií.",
    ]),
    "ekonomia-7": ("Menová politika ovplyvňuje cenu a dostupnosť peňazí v ekonomike.", [
        "V eurozóne ju vykonáva ECB spolu s národnými centrálnymi bankami.",
        "Hlavné nástroje sú úrokové sadzby, operácie na voľnom trhu a povinné rezervy.",
        "Nižšie úroky podporujú úvery a dopyt; vyššie úroky tlmia infláciu.",
        "Spoločná mena odstraňuje kurzové riziko a uľahčuje obchod.",
        "Nevýhodou je jedna politika pre rozdielne ekonomické podmienky členských štátov.",
    ]),
    "ekonomia-8": ("Otvorená ekonomika obchoduje a presúva kapitál so zahraničím; uzavretá nie.", [
        "IS predstavuje rovnováhu na trhu tovarov, LM na trhu peňazí.",
        "Ich priesečník určuje rovnovážny produkt a úrokovú mieru.",
        "Expanzívna fiškálna politika posúva IS doprava.",
        "Expanzívna menová politika posúva LM doprava.",
        "SR je otvorená exportná ekonomika: získava trhy a investície, ale je citlivá na cudzie krízy.",
    ]),
    "ekonomia-9": ("EÚ je integračné zoskupenie, v ktorom štáty časť rozhodovania vykonávajú spoločne.", [
        "Komisia navrhuje a vykonáva politiky, Parlament a Rada prijímajú legislatívu.",
        "Európska rada určuje hlavné politické smerovanie.",
        "Slovensko má zástupcov v Parlamente, Rade, Komisii a ďalších orgánoch.",
        "Členstvo prináša jednotný trh, eurofondy, investície a voľný pohyb.",
        "Výzvy sú bezpečnosť, energia, klíma, starnutie a konkurencieschopnosť.",
    ]),
    "ekonomia-10": ("Ekonomická integrácia postupne odstraňuje prekážky medzi národnými ekonomikami.", [
        "Pásmo voľného obchodu ruší clá medzi členmi.",
        "Colná únia pridáva spoločné clá voči tretím krajinám.",
        "Spoločný trh umožňuje voľný pohyb tovaru, služieb, osôb a kapitálu.",
        "Hospodárska a menová únia koordinuje politiky a používa spoločnú menu.",
        "SR získava trh a investície, ale čelí silnej konkurencii a strate časti autonómie.",
    ]),
    "ekonomia-11": ("Medzinárodný obchod prepája krajiny, ale zároveň vytvára závislosť a tlak na ochranu trhu.", [
        "Liberalizmus odstraňuje bariéry; protekcionizmus chráni domácich výrobcov.",
        "Trendmi sú globálne hodnotové reťazce, obchod so službami, digitalizácia a väčšia geopolitická neistota.",
        "Nástroje sú clá, kvóty, subvencie, normy a obchodné dohody.",
        "WTO vytvára pravidlá, rieši spory a podporuje liberalizáciu.",
        "Rozvinuté aj rozvojové štáty kombinujú otvorenosť s ochranou citlivých odvetví; rozvojové žiadajú priestor chrániť vznikajúci priemysel.",
        "SR je malá, veľmi otvorená a exportne závislá ekonomika v rámci EÚ.",
    ]),
    "ekonomia-12": ("Medzinárodný pohyb kapitálu znamená presun investícií a úverov medzi krajinami.", [
        "Priama investícia dáva investorovi dlhodobý vplyv alebo kontrolu.",
        "Portfóliová investícia je nákup cenných papierov bez kontroly firmy.",
        "Hostiteľský štát získava kapitál, prácu a technológie, ale môže byť závislý.",
        "Domovský štát získava výnosy a trhy, ale môže prísť o časť pracovných miest.",
        "SR podporuje investície daňovou úľavou, dotáciou, príspevkom na pracovné miesta či majetkom.",
    ]),
    "ekonomia-13": ("Agenda 2030 a Zelená dohoda smerujú rozvoj k sociálnej, ekonomickej a environmentálnej udržateľnosti.", [
        "Agenda 2030 obsahuje 17 cieľov udržateľného rozvoja OSN.",
        "Zelená dohoda má viesť EÚ ku klimatickej neutralite do roku 2050.",
        "Vznikli ako reakcia na klimatickú zmenu, chudobu, nerovnosť a neudržateľnú spotrebu zdrojov.",
        "Štáty zaväzujú plánovať, prijímať opatrenia, financovať zmenu a pravidelne hodnotiť pokrok.",
        "Prínosom sú inovácie, úspory energií a nové odvetvia.",
        "Nákladom sú vysoké investície a transformácia energetiky a priemyslu.",
        "SR ich realizuje stratégiou Slovensko 2030, plánom obnovy, energetickými a klimatickými politikami.",
    ]),
    "ekonomia-14": ("Peniaze sú všeobecne prijímaný prostriedok výmeny, platenia a uchovania hodnoty.", [
        "Funkcie: prostriedok výmeny, účtovná jednotka a uchovávateľ hodnoty.",
        "Formy: hotovostné, bezhotovostné a elektronické peniaze.",
        "Peniaze sú širší pojem; mena je konkrétna národná alebo menová jednotka.",
        "Menová sústava určuje menovú jednotku, emisiu, obeh, kurzové pravidlá a úlohu centrálnej banky.",
        "Eurosystém tvorí ECB a centrálne banky krajín používajúcich euro.",
        "CBDC je digitálna mena centrálnej banky; digitálne euro zatiaľ nie je zavedené.",
    ]),
    "ekonomia-15": ("ECB riadi spoločnú menovú politiku eurozóny a NBS ju vykonáva na Slovensku.", [
        "Hlavným cieľom ECB je cenová stabilita.",
        "Orgány ECB: Rada guvernérov, Výkonná rada a Generálna rada.",
        "NBS je centrálna banka SR; jej najvyšším orgánom je Banková rada.",
        "NBS vykonáva operácie Eurosystému, spravuje hotovosť, štatistiku a dohľad.",
        "Guvernér NBS je členom Rady guvernérov ECB.",
    ]),
    "ekonomia-16": ("Bankový systém zabezpečuje platby, úvery, vklady a prenos menovej politiky.", [
        "Dvojstupňový systém tvorí centrálna banka a obchodné banky.",
        "SR prešla od jednostupňového systému cez transformáciu a privatizáciu k stabilnému systému v Eurosystéme.",
        "Nebankové inštitúcie sú poisťovne, fondy, obchodníci s cennými papiermi a leasingové firmy.",
        "Banky podporujú ekonomiku, ale problémy bánk môžu ohroziť celý systém.",
        "Riziká: úverové, trhové, likviditné, operačné a úrokové.",
        "Dohľad a regulácia vyžadujú kapitál, likviditu a riadne riadenie rizík.",
    ]),
    "ekonomia-17": ("Obchodná banka prijíma peniaze, poskytuje úvery a zarába najmä na úrokovom rozdiele a poplatkoch.", [
        "Pasívne operácie získavajú zdroje, napríklad vklady.",
        "Aktívne operácie používajú zdroje, najmä úvery a investície.",
        "Neutrálne operácie sú platby, záruky, úschova a poradenstvo.",
        "Produkty možno členiť na vkladové, úverové, platobné a investičné.",
        "Úverová zmluva určuje sumu, splatnosť, úrok, zabezpečenie a sankcie.",
    ]),
    "ekonomia-18": ("Na trhu práce sa stretáva ponuka práce zamestnancov s dopytom zamestnávateľov.", [
        "Subjekty sú zamestnanci, zamestnávatelia, štát a odbory.",
        "Vyjednávanie môže byť individuálne alebo kolektívne.",
        "Rovnováha vzniká pri zhode ponúkanej a požadovanej práce a mzdy.",
        "Mzdy a nezamestnanosť ovplyvňujú produktivita, vzdelanie, región, cyklus a legislatíva.",
        "Minimálna mzda sa určuje dohodou sociálnych partnerov alebo zákonným automatom.",
    ]),
    "ekonomia-19": ("Okunov zákon spája rast ekonomiky s poklesom nezamestnanosti.", [
        "Pri raste produkcie firmy viac vyrábajú a zamestnávajú; pri poklese opačne.",
        "Dlhodobý rast tvorí práca, kapitál, produktivita, vzdelanie a technológie.",
        "Úspory financujú investície, ktoré zvyšujú kapitál a výstup.",
        "Pre klesajúce výnosy samotný kapitál nestačí; dlhodobo rozhoduje technologický pokrok.",
        "Automatizácia a AI rušia rutinné úlohy, ale tvoria nové práce a menia potrebné zručnosti.",
    ]),
    "ekonomia-20": ("Finančný manažment rozhoduje, odkiaľ podnik získa peniaze a ako ich použije.", [
        "Financovanie: vlastné alebo cudzie zdroje.",
        "Investovanie: výber majetku a projektov s vhodným výnosom a rizikom.",
        "Riadenie pracovného kapitálu: zásoby, pohľadávky, hotovosť a záväzky.",
        "Hlavným cieľom je finančná stabilita a dlhodobé zvyšovanie hodnoty podniku.",
        "Finančné prostredie tvoria trhy, banky, poisťovne, nástroje a produkty.",
        "Financie prepájajú výrobu, marketing, ľudské zdroje a účtovníctvo.",
    ]),
    "ekonomia-21": ("Náklady vyjadrujú spotrebu zdrojov podniku a možno ich členiť podľa viacerých hľadísk.", [
        "Priame priradíme výrobku; nepriame sú spoločná réžia.",
        "Fixné sa s objemom nemenia; variabilné sa menia s výrobou.",
        "Automatizácia zvyšuje odpisy a réžiu, outsourcing mení fixné náklady na externé služby.",
        "Agentúrna práca zvyšuje pružnosť personálnych nákladov a internacionalizácia pridáva dopravu, kurzové a koordinačné náklady.",
        "Tradičná kalkulácia rozdeľuje réžiu jednou základňou.",
        "ABC priraďuje náklady najprv činnostiam a potom produktom podľa cost driverov.",
    ]),
    "ekonomia-22": ("Majetok podniku sú zdroje, ktoré podnik vlastní a používa na svoju činnosť.", [
        "Dlhodobý majetok slúži dlhšie; obežný sa rýchlo spotrebuje alebo premieňa.",
        "Oceňovanie môže vychádzať z historickej alebo reálnej ceny.",
        "Odpisy rozkladajú hodnotu dlhodobého majetku do viacerých období.",
        "Účtovné odpisy vyjadrujú reálne opotrebenie, daňové odpisy určuje zákon pre výpočet dane.",
        "Kolobeh: peniaze – zásoby – výroba – pohľadávky – peniaze.",
        "Pracovný kapitál je obežný majetok mínus krátkodobé záväzky; cieľom je likvidita bez zbytočného viazania peňazí.",
    ]),
    "ekonomia-23": ("Majetok podniku musí byť krytý vlastnými alebo cudzími zdrojmi.", [
        "Majetok, teda aktíva, sa rovná pasívam: vlastnému imaniu plus záväzkom.",
        "Vlastníci majú reziduálny nárok a výnos cez zisk alebo rast hodnoty.",
        "Veritelia majú prednostný nárok a dohodnutú istinu s úrokom.",
        "Kapitálová štruktúra je pomer vlastného a cudzieho kapitálu.",
        "Zisk možno vyplatiť vlastníkom, uložiť do fondov alebo ponechať v podniku na ďalší rozvoj.",
        "Sledujeme zadlženosť, samofinancovanie, finančnú páku a úrokové krytie.",
    ]),
    "ekonomia-24": ("Účtovné výkazy ukazujú majetok, financovanie, výsledok hospodárenia a pohyb peňazí.", [
        "Súvaha ukazuje aktíva a pasíva k určitému dátumu.",
        "Výkazy používajú manažéri, vlastníci, banky, investori, dodávatelia aj štát.",
        "Výsledovka porovnáva výnosy a náklady a určuje zisk alebo stratu.",
        "Náklady sú spotreba zdrojov, výnosy ekonomický prospech; ich rozdiel tvorí výsledok hospodárenia.",
        "Cash flow ukazuje skutočné príjmy a výdavky.",
        "Výnos nie je vždy prijatá hotovosť a náklad nie je vždy okamžitý výdavok.",
        "Firma môže byť zisková, ale skrachovať pre nedostatok hotovosti.",
    ]),
    "ekonomia-25": ("Podvojné účtovníctvo zachytáva každú operáciu najmenej na dvoch účtoch.", [
        "Dodávateľ: podnik mu dlhuje, vzniká záväzok.",
        "Odberateľ: dlhuje podniku, vzniká pohľadávka.",
        "Akcia znamená vlastnícky podiel a dividendu; dlhopis dlh a úrok.",
        "Mzdy spájajú hrubú mzdu, odvody, daň a čistú mzdu.",
        "Priama daň znižuje zisk; nepriamu daň podnik vyberie a odvedie štátu.",
        "Pre manažment účtovníctvo kontroluje internú efektívnosť aj vzťahy s bankami, štátom a obchodnými partnermi.",
    ]),
    "ekonomia-26": ("Finančná analýza hodnotí zdravie firmy a porovnáva ho v čase aj s konkurenciou.", [
        "Likvidita: schopnosť zaplatiť krátkodobé záväzky.",
        "Zadlženosť: podiel cudzieho kapitálu a finančné riziko.",
        "Aktivita sleduje využitie majetku; ukazovatele odhaľujú riziká, príležitosti a umožňujú benchmarking.",
        "Rentabilita: ROA je zisk z majetku, ROE z kapitálu vlastníkov, ROS z tržieb.",
        "FCF je voľná hotovosť; ROIC výnos z investovaného kapitálu.",
        "EVA a MVA merajú tvorbu hodnoty; DuPont vysvetlí, z čoho vzniká ROE.",
    ]),
    "ekonomia-27": ("Časová hodnota peňazí znamená, že euro dnes má vyššiu hodnotu než euro v budúcnosti.", [
        "Budúca hodnota ukazuje, na koľko dnešné peniaze narastú.",
        "Súčasná hodnota prepočítava budúcu sumu na dnešok.",
        "Anuita je séria rovnakých platieb počas určitého času.",
        "Perpetuita je rovnaká platba bez časového konca.",
        "Efektívna ročná sadzba umožňuje porovnať produkty s rôznym pripisovaním úrokov.",
    ]),
    "ekonomia-28": ("Cena peňazí je úrok a cena kapitálu je požadovaný výnos poskytovateľov financovania.", [
        "Nominálny úrok nezohľadňuje infláciu; reálny ju odpočítava.",
        "Cena cudzieho kapitálu je úrok, cena vlastného kapitálu očakávaný výnos vlastníkov.",
        "Výnosová krivka porovnáva úroky podľa splatnosti.",
        "Invertovaná krivka môže signalizovať očakávanú recesiu.",
        "Vyššie úroky priťahujú kapitál, zvyšujú dopyt po mene a môžu ju posilniť.",
    ]),
    "ekonomia-29": ("Vo financiách vyšší očakávaný výnos zvyčajne znamená vyššie riziko.", [
        "Izolované riziko meriame rozptylom alebo smerodajnou odchýlkou výnosov.",
        "Portfólio spája viac aktív a jeho riziko závisí aj od ich vzájomného pohybu.",
        "Diverzifikácia znižuje špecifické, nie systematické trhové riziko.",
        "CAPM spája požadovaný výnos s bezrizikovou sadzbou, betou a trhovou prémiou.",
        "Úspory odkladajú spotrebu a chránia rezervu; investície prijímajú riziko s cieľom výnosu.",
        "Na Slovensku možno investovať do vkladov, fondov, akcií, dlhopisov, nehnuteľností či dôchodkového sporenia.",
    ]),
    "ekonomia-30": ("Kapitálové investície hodnotíme podľa toho, či zvýšia hodnotu podniku.", [
        "Doba splatnosti ukáže, za ako dlho sa vráti vložený kapitál.",
        "NPV je dnešná hodnota budúcich tokov mínus počiatočná investícia; prijímame NPV nad nulou.",
        "IRR je výnosnosť, pri ktorej sa NPV rovná nule; porovnáva sa s cenou kapitálu.",
        "PI je pomer prínosov k investícii; nad jedna je projekt prijateľný.",
        "Pri konflikte projektov má prednosť NPV; pri obmedzenom rozpočte pomáha PI.",
    ]),
    "manazment-1": ("Manažment je proces dosahovania cieľov prostredníctvom ľudí a zdrojov.", [
        "Proces tvorí plánovanie, organizovanie, vedenie a kontrola.",
        "Ako veda vytvára poznatky a metódy riadenia.",
        "Ako profesia vyžaduje odbornosť, zodpovednosť a etiku.",
        "Manažér rozhoduje, koordinuje ľudí a nesie zodpovednosť za výsledky.",
        "Kompetencie treba rozvíjať: odborné, sociálne, komunikačné a koncepčné.",
    ]),
    "manazment-2": ("Prístupy k manažmentu sa vyvíjali od kontroly práce k pružnému riadeniu ľudí, procesov a technológií.", [
        "Klasické prístupy: efektívnosť práce, pravidlá, hierarchia a deľba práce.",
        "Behaviorálny prístup zdôrazňuje človeka, motiváciu a skupiny.",
        "Systémový prístup chápe organizáciu ako prepojený celok.",
        "Situačný prístup volí spôsob riadenia podľa okolností.",
        "Malá firma potrebuje pružnosť, veľká viac pravidiel; výroba štandardizáciu, tvorivá firma voľnejšiu spoluprácu.",
        "Digitalizácia mení manažéra z kontrolóra na koordinátora, kouča a prácu s dátami.",
    ]),
    "manazment-3": ("Manažérske funkcie tvoria prepojený cyklus riadenia organizácie.", [
        "Plánovanie určuje ciele a postup.",
        "Organizovanie rozdeľuje úlohy, právomoci a zdroje.",
        "Vedenie motivuje a usmerňuje ľudí.",
        "Kontrola porovnáva výsledok s plánom a opravuje odchýlky.",
        "V malom podniku ich často vykonáva jedna osoba; pomáha CRM, ERP, účtovný a projektový softvér.",
    ]),
    "manazment-4": ("Plánovanie určuje, kam organizácia smeruje a ako sa tam dostane.", [
        "Strategické plány sú dlhodobé a určujú smer.",
        "Taktické plány rozpracujú stratégiu pre útvary.",
        "Operatívne plány riešia krátkodobé konkrétne úlohy.",
        "Podnikateľský model vysvetľuje, ako firma vytvára a získava hodnotu.",
        "Podnikateľský plán model rozpracuje do trhu, financií, činností a rizík.",
    ]),
    "manazment-5": ("Organizačná štruktúra určuje rozdelenie práce, právomocí a komunikácie.", [
        "Funkčná štruktúra delí firmu podľa odborností.",
        "Divizionálna podľa produktov, regiónov alebo zákazníkov.",
        "Maticová spája funkčné a projektové riadenie, ale má dvojitú autoritu.",
        "Pri tvorbe sa rozhoduje o špecializácii, centralizácii, formalizácii, rozpätí riadenia a deľbe právomocí.",
        "Plochá štruktúra zrýchľuje komunikáciu, vysoká posilňuje kontrolu.",
        "Formálna komunikácia ide určenými kanálmi, neformálna vzniká medzi ľuďmi.",
    ]),
    "manazment-6": ("Leadership je schopnosť ovplyvniť ľudí, aby dobrovoľne smerovali k spoločnému cieľu.", [
        "Teórie skúmajú vlastnosti lídra, jeho správanie a vhodnosť štýlu pre situáciu.",
        "Štýl môže byť autokratický, demokratický alebo liberálny.",
        "Moc je schopnosť ovplyvniť; právomoc je formálne oprávnenie rozhodovať.",
        "Zdroje moci: pozícia, odmena, donútenie, odbornosť a osobný vplyv.",
        "V projekte líder vedie dočasný tím bez vždy priamej autority, preto potrebuje komunikáciu a dôveru.",
    ]),
    "manazment-7": ("Kontrola zisťuje, či skutočné výsledky zodpovedajú plánu.", [
        "Postup: stanoviť štandard, zmerať výsledok, porovnať a napraviť odchýlku.",
        "Predbežná kontrola pôsobí pred činnosťou, priebežná počas nej, následná po nej.",
        "Kontrola môže byť interná, externá, strategická alebo operatívna.",
        "Reporting prináša manažérovi pravidelné informácie a upozorňuje na odchýlky.",
        "Podporou sú informačné systémy, dashboardy, KPI a automatické reporty.",
    ]),
    "manazment-8": ("Rozhodovanie je výber najvhodnejšieho riešenia z viacerých možností.", [
        "Proces: problém, kritériá, alternatívy, výber, realizácia a kontrola.",
        "Behaviorálny prístup počíta s obmedzenými informáciami a ľudskými chybami.",
        "Kvantitatívny používa dáta, modely a výpočty.",
        "Individuálne rozhodovanie je rýchle; skupinové má viac pohľadov, ale trvá dlhšie.",
        "Controlling dodáva plány, rozpočty, analýzu odchýlok a podklady na rozhodnutie.",
    ]),
    "manazment-9": ("Organizačná kultúra je súbor spoločných hodnôt, noriem a spôsobov správania vo firme.", [
        "Artefakty sú viditeľné prejavy, napríklad jazyk, symboly a rituály.",
        "Hodnoty a normy hovoria, čo organizácia považuje za správne.",
        "Základné predpoklady sú hlboké, často neuvedomované presvedčenia.",
        "Hofstede sleduje napríklad vzdialenosť od moci, individualizmus a vyhýbanie sa neistote.",
        "Nižšia mocenská vzdialenosť a tolerancia neistoty zvyčajne podporujú nápady a inovácie.",
    ]),
    "manazment-10": ("Nábor získava uchádzačov a výber rozhoduje, ktorý z nich je najvhodnejší.", [
        "Zdroje môžu byť interné alebo externé.",
        "Vyhľadávanie: inzercia, sociálne siete, školy, agentúry a odporúčania.",
        "Výber: životopis, rozhovor, test, assessment centrum a referencie.",
        "Chyby: predsudky, halo efekt, nejasné kritériá a diskriminácia.",
        "Pracovná zmluva musí obsahovať druh práce, miesto, deň nástupu a mzdové podmienky.",
    ]),
    "manazment-11": ("Manažment ľudských zdrojov zabezpečuje, aby mala organizácia správnych ľudí a vedela ich rozvíjať.", [
        "Funkcie: plánovanie, nábor, výber, adaptácia a evidencia.",
        "Ďalej hodnotenie výkonu, odmeňovanie, vzdelávanie a kariéra.",
        "HR má byť prepojené so stratégiou organizácie.",
        "Výzvy SR: nedostatok ľudí, starnutie, odchod talentov a regionálne rozdiely.",
        "Ďalšie výzvy sú digitalizácia, AI, hybridná práca a potreba nových zručností.",
    ]),
    "manazment-12": ("Manažment výkonu je priebežný proces plánovania, sledovania, hodnotenia a rozvoja práce.", [
        "Najprv sa dohodnú ciele, ukazovatele a očakávania.",
        "Počas obdobia sa poskytuje spätná väzba a odstraňujú prekážky.",
        "Hodnotenie ovplyvňuje odmenu a bonusy.",
        "Odhaľuje potreby vzdelávania, rozvoja a kariérneho postupu.",
        "Pomáha plánovať pracovnú silu a prijímať personálne opatrenia.",
    ]),
    "manazment-13": ("Motivácia vysvetľuje, čo ľudí aktivuje a usmerňuje ich správanie.", [
        "Maslow: potreby od základných až po sebarealizáciu.",
        "Herzberg: hygienické faktory bránia nespokojnosti, motivátory zvyšujú výkon.",
        "Vroom: človek sa snaží, ak verí vo výkon, odmenu a jej hodnotu.",
        "Adams: ľudia porovnávajú spravodlivosť svojho vkladu a odmeny.",
        "Manažér kombinuje mzdu, uznanie, zodpovednosť, rast a férové podmienky.",
        "Príklad: výkonový bonus podporí očakávanie odmeny, pochvala a samostatná úloha pôsobia ako Herzbergove motivátory.",
    ]),
    "manazment-14": ("V kríze má organizácia najprv znižovať personálne náklady miernejšími opatreniami a až potom prepúšťaním.", [
        "Mäkké kroky: stop náboru, obmedzenie nadčasov, benefitov, pracovného času či dohody.",
        "Tvrdé kroky: prepúšťanie, hromadné prepúšťanie alebo zrušenie miest.",
        "Downsizing musí byť plánovaný, zákonný, komunikovaný a férový.",
        "Outplacement pomáha prepusteným nájsť prácu a chráni reputáciu aj morálku firmy.",
        "Pracovný pomer sa končí dohodou, výpoveďou, okamžite, v skúšobnej dobe alebo uplynutím času.",
    ]),
    "manazment-15": ("Odmeňovanie zahŕňa mzdu, bonusy, benefity aj nefinančné uznanie.", [
        "Systém má byť spravodlivý, motivujúci, konkurencieschopný a finančne udržateľný.",
        "Štát určuje minimálnu mzdu, odvody, dane a pracovné pravidlá.",
        "Trh práce ovplyvňuje cenu nedostatkových profesií.",
        "Konkurencia núti firmu porovnávať mzdy a benefity.",
        "Inflácia a ekonomický vývoj menia reálnu hodnotu odmien a možnosti firmy.",
    ]),
    "manazment-16": ("Rozvoj dáva zamestnancovi nové schopnosti a kariérny manažment smer jeho pracovného rastu.", [
        "Organizácia spája potreby firmy s cieľmi a potenciálom človeka.",
        "Kariérna kotva je hodnota, ktorej sa človek pri kariérnom rozhodnutí nechce vzdať.",
        "Kotvy môžu byť odbornosť, vedenie, istota, autonómia, podnikavosť, služba či výzva.",
        "Trendy: individuálne cesty, mentoring, koučing, rotácia, online učenie a reskilling.",
        "Kariéra už nemusí znamenať iba vertikálny postup na vyššiu pozíciu.",
    ]),
    "manazment-17": ("Časové plánovanie projektu určuje úlohy, ich poradie, trvanie, zdroje a termíny.", [
        "Ganttov diagram zobrazuje úlohy na časovej osi.",
        "CPM nájde kritickú cestu, ktorej oneskorenie posunie celý projekt.",
        "PERT používa optimistický, najpravdepodobnejší a pesimistický odhad času.",
        "Participatívne plánovanie zapája členov tímu do odhadov a rozhodnutí.",
        "Zapojenie zvyšuje presnosť plánu, prijatie zodpovednosti a odhaľuje riziká.",
        "Príklad: projektový manažér s tímom rozloží projekt na úlohy, Product Owner určí priority a odborníci odhadnú trvanie.",
    ]),
    "manazment-18": ("Operačný manažment premieňa vstupy na výrobky alebo služby.", [
        "Riadi kapacitu, kvalitu, zásoby, procesy, technológie a produktivitu.",
        "Efektívny systém dosahuje kvalitu, rýchlosť, pružnosť a nízke náklady.",
        "Priemysel 4.0 prepája fyzickú výrobu s dátami a digitálnymi systémami.",
        "Technológie: IoT, roboty, AI, cloud, big data, digitálne dvojča a 3D tlač.",
        "Prínosom je prediktívna údržba, automatizácia, sledovanie a pružná výroba.",
    ]),
    "manazment-19": ("Logistika riadi tok materiálu, tovaru, informácií a peňazí od dodávateľa k zákazníkovi.", [
        "Zásobovacia logistika zabezpečuje vstupy.",
        "Výrobná riadi pohyb vo výrobe, distribučná dodanie zákazníkovi a spätná návraty či odpad.",
        "Individuálne obstarávanie objednáva podľa potreby: málo zásob, vyššie riziko čakania.",
        "Obstarávanie na sklad zvyšuje istotu, ale viaže kapitál a priestor.",
        "JIT dodáva presne k výrobe: nízke zásoby, ale vysoká závislosť od dodávateľa.",
    ]),
    "manazment-20": ("Doprava zabezpečuje fyzický pohyb materiálu a tovaru v podniku aj mimo neho.", [
        "Vnútropodniková doprava používa dopravníky, vozíky, žeriavy či AGV.",
        "Cestná je pružná, železničná vhodná na veľké objemy, vodná lacná a pomalá, letecká rýchla a drahá.",
        "Výber závisí od ceny, času, objemu, vzdialenosti a vlastností nákladu.",
        "Intermodálna doprava kombinuje viac druhov bez prekladania samotného nákladu.",
        "Doprava je prepojená so skladovaním, manipuláciou a ochranným balením.",
    ]),
    "manazment-21": ("Podnikateľ samostatne a na vlastné riziko hľadá príležitosť a vytvára hodnotu so zámerom dosiahnuť zisk.", [
        "Vlastnosti: iniciatíva, tvorivosť, vytrvalosť, zodpovednosť a prijatie rizika.",
        "Živnosť je jednoduchá, ale podnikateľ ručí celým majetkom.",
        "s.r.o. je samostatná právnická osoba a spoločníci ručia obmedzene.",
        "a.s. získava kapitál cez akcie a má náročnejšiu správu.",
        "Ďalšie formy sú v.o.s., k.s., j.s.a. a družstvo.",
    ]),
    "manazment-22": ("Marketing zisťuje potreby zákazníkov a vytvára ponuku, ktorá ich uspokojí so ziskom.", [
        "Trh tvoria existujúci a potenciálni kupujúci.",
        "Segmentácia rozdelí trh na podobné skupiny.",
        "STP: segmentácia, výber cieľového segmentu a pozicionovanie v mysli zákazníka.",
        "Segmenty pomáhajú upraviť produktový mix pre rôzne potreby.",
        "Príklad Volvo: rodinám ponúkne bezpečné SUV, ekologickým zákazníkom elektrické modely a firmám flotilové riešenia.",
        "Štruktúrované dáta sú tabuľky a CRM; neštruktúrované texty, obrázky, recenzie a sociálne siete.",
        "Spracovanie: štatistika a databázové dotazy pri štruktúrovaných dátach, textová či sentimentálna analýza pri neštruktúrovaných.",
    ]),
    "manazment-23": ("Spotrebiteľský nákup B2C a organizačný nákup B2B sa líšia počtom ľudí, racionalitou a zložitosťou.", [
        "B2C často ovplyvňujú emócie, rodina, kultúra, značka a osobné potreby.",
        "Proces B2C: potreba, informácie, hodnotenie, kúpa a správanie po kúpe.",
        "B2B má viac účastníkov, formálne kritériá, vyššiu hodnotu a dlhší proces.",
        "Spotrebiteľa možno vysvetliť Maslowom, emóciami a vnímanou hodnotou.",
        "Nákupné oddelenie motivuje cena, kvalita, riziko, spoľahlivosť a osobná zodpovednosť.",
        "Vroom vysvetľuje očakávaný výsledok nákupu a Adams potrebu férového porovnania ponúk a podmienok.",
    ]),
    "manazment-24": ("Marketingový mix je kombinácia nástrojov, ktorými firma ovplyvňuje cieľový trh.", [
        "4P: produkt, cena, distribúcia a komunikácia.",
        "Pri službách sa pridávajú ľudia, procesy a materiálne prostredie, teda 7P.",
        "Príklad McDonald’s: produkt je menu, cena balíčky, distribúcia prevádzky a rozvoz, komunikácia reklama a aplikácia.",
        "Výrobný podnik zdôrazňuje hmotný produkt, zásoby, výrobu a distribúciu.",
        "Služba je nehmotná, vzniká často pri kontakte so zákazníkom a nedá sa skladovať.",
        "Preto sú pri službách mimoriadne dôležití zamestnanci, proces a dôkaz kvality.",
    ]),
    "manazment-25": ("Produkt je čokoľvek, čo uspokojuje potrebu zákazníka.", [
        "Produktový rad je skupina príbuzných produktov; produktový mix sú všetky rady firmy.",
        "Úrovne produktu: jadro úžitku, základný, očakávaný, rozšírený a potenciálny produkt.",
        "Uvedenie: informovať trh a získať prvých zákazníkov.",
        "Rast: rozširovať distribúciu a odlíšiť sa od konkurencie.",
        "Zrelosť: brániť podiel a inovovať; pokles: obmedziť, zmeniť alebo stiahnuť produkt.",
    ]),
    "manazment-26": ("Cena musí pokryť náklady, zodpovedať hodnote pre zákazníka a reagovať na konkurenciu.", [
        "Nákladová tvorba vychádza z nákladov a prirážky.",
        "Hodnotová vychádza z vnímanej hodnoty; konkurenčná z cien súperov.",
        "Nový produkt môže použiť vysokú zbernú cenu alebo nízku penetračnú cenu.",
        "V dokonalej konkurencii cenu určuje trh, monopol má najväčšiu cenovú silu.",
        "V oligopole firmy navzájom sledujú zmeny cien a často na ne reagujú.",
    ]),
    "manazment-27": ("Distribučný kanál je cesta produktu od výrobcu ku konečnému zákazníkovi.", [
        "Sprostredkovatelia prekonávajú vzdialenosť, čas a rozdiel v množstve.",
        "Veľkoobchod nakupuje vo veľkom a predáva ďalším podnikom.",
        "Maloobchod predáva konečnému spotrebiteľovi a rieši sortiment aj službu.",
        "SCM koordinuje dodávateľov, výrobu, sklady, dopravu a zákazníkov.",
        "Cieľom je dostupnosť produktu pri nízkych celkových nákladoch a zásobách.",
    ]),
    "manazment-28": ("Marketingová komunikácia prenáša správu od firmy k príjemcovi a spätnou väzbou overuje účinok.", [
        "Prvky: odosielateľ, kódovanie, správa, médium, dekódovanie, príjemca, reakcia, spätná väzba a šum.",
        "Príklad Kofola: firma zakóduje emóciu do vianočnej reklamy, šíri ju médiami a reakcie sleduje cez predaj a sociálne siete.",
        "Integrovaná komunikácia znamená jednotné posolstvo vo všetkých kanáloch.",
        "Externá komunikácia musí byť v súlade s tým, čo vedia a robia zamestnanci.",
        "Internet je globálna sieť umožňujúca digitálnu výmenu informácií.",
        "Riešenia: web, e-mail, sociálne siete, reklama, chat, SEO a zákaznícky portál.",
    ]),
    "manazment-29": ("Reklama, podpora predaja a PR majú odlišný cieľ aj časový účinok.", [
        "Reklama je platená neosobná komunikácia na budovanie povedomia a značky.",
        "Podpora predaja dáva krátkodobý stimul, napríklad zľavu, kupón alebo vzorku.",
        "PR buduje dôveru a vzťahy s verejnosťou cez médiá, udalosti a reputáciu.",
        "Pri reklame sa určuje cieľ, rozpočet, správa, médium a meranie účinku.",
        "Pri podpore predaja sa volí stimul, cieľová skupina, dĺžka akcie a podmienky; PR používa médiá, podujatia, sponzoring a krízovú komunikáciu.",
        "Pri CSR musia byť tvrdenia pravdivé, transparentné a doložené, inak vzniká greenwashing.",
    ]),
    "manazment-30": ("Podnikateľský nápad musí riešiť konkrétny problém konkrétneho zákazníka udržateľným spôsobom.", [
        "Súčasti: problém, cieľový zákazník, riešenie, hodnota, príjmy, náklady a zdroje.",
        "Nápady vznikajú z problémov, trendov, skúseností, technológií a spätnej väzby.",
        "Techniky: brainstorming, pozorovanie, rozhovory, mind map a design thinking.",
        "Validácia overuje záujem rozhovormi, prototypom alebo MVP ešte pred veľkou investíciou.",
        "Web: vybrať názov a doménu, overiť ju, registrovať, zvoliť hosting, vytvoriť stránku a zabezpečiť ju.",
    ]),
}


topics = json.loads(TOPICS.read_text(encoding="utf-8"))
if len(topics) != 60 or set(S) != {topic["id"] for topic in topics}:
    missing = {topic["id"] for topic in topics} - set(S)
    extra = set(S) - {topic["id"] for topic in topics}
    raise RuntimeError(f"Kostry nesedia s témami. Chýbajú: {missing}; navyše: {extra}")

data = []
for topic in topics:
    start, points = S[topic["id"]]
    data.append({
        "id": topic["id"],
        "subject": topic["subject"],
        "number": topic["number"],
        "title": topic["title"],
        "start": start,
        "points": points,
    })

OUTPUT.parent.mkdir(parents=True, exist_ok=True)
OUTPUT.write_text(
    "window.__SKELETONS__ = "
    + json.dumps(data, ensure_ascii=False, indent=2)
    + ";\n",
    encoding="utf-8",
)
print(json.dumps({"skeletons": len(data), "points": sum(len(item["points"]) for item in data)}))
